Unit handling and round-trip .nc conversion fixes
cfs-energy/cfspopcon pull request #13
Opened 2023-11-29 21:12 UTC by tbody-cfs

2023-11-29 21:12 UTC, tbody-cfs commented
Closes #10

2023-11-29 21:40 UTC, hassec commented
Before merging this I'd like to make sure we have a way to reproduce the error  described in #10. I've tried locally without luck so far and added a test that would catch the in #10 described problem, see #14

2023-11-29 22:31 UTC, tbody-cfs commented
Think I've figured out how to reproduce the error. To fix https://github.com/cfs-energy/cfspopcon/actions/runs/7038938605/job/19156931593?pr=7, I added `netcdf4` to the poetry environment. Then I can reproduce #10 with
```
poetry add netcdf4
rm -rf .venv
poetry install
poetry run python tests/regression_results/generate_regression_results.py
poetry run pytest
```

2023-11-29 22:46 UTC, tbody-cfs commented
And then I fixed it again https://github.com/cfs-energy/cfspopcon/actions/runs/7039432837/job/19158407447?pr=13 🥳🥳🥳

2023-11-30 18:22 UTC, hassec requested changes
Just a small change request to add a comment to the conversion logic. 

I'd prefer to have updates to the `poetry.lock` in a separate PR but since you already fixed the mypy stuff here let's merge this as is. But in the future we should try and avoid poetry updates in PRs that have other changes.

2023-11-30 18:22 UTC, hassec commented on tests/test_unit_handling/test_conversions.py
> +import warnings
Thanks for adding this test :)

2023-11-30 18:22 UTC, hassec commented on cfspopcon/unit_handling/default_units.py
> +    if unit is None:
Nice catch! 👍

2023-11-30 18:22 UTC, hassec commented on cfspopcon/file_io.py
> +    if val.dtype == object or val.dtype.type == np.str_:
```suggestion
    # scipy i/o yields objects for strings while netcdf4 yields np.str_ 
    if val.dtype == object or val.dtype.type == np.str_:
```

2023-11-30 19:09 UTC, hassec commented on cfspopcon/file_io.py
> +    # scipy i/o yields objects for strings while netcdf4 yields np.str_
```suggestion
    # scipy i/o yields objects for strings while netcdf4 yields np.str_
```

2023-11-30 19:15 UTC, merged