Draft: Update radas to v1
cfs-energy/cfspopcon pull request #31
Opened 2024-03-22 18:47 UTC by tbody-cfs

Removes the radas submodule and replaces it with a pip-installed version.

2024-03-22 19:59 UTC, hassec commented on .github/workflows/workflow_actions.yml
> +          key: radas-${{ hashFiles('./radas_dir')}}
`radas_dir` can't be the source of the hash. Now that radas is a poetry dependency and thus part of `poetry.lock` using that as a hash is probably ok

2024-03-22 20:01 UTC, hassec requested changes

2024-03-22 20:01 UTC, hassec commented on .github/workflows/workflow_actions.yml
>            path: radas
should probably change to `radas_dir`

2024-03-22 20:01 UTC, hassec commented on .github/workflows/workflow_actions.yml
> +          key: radas-${{ hashFiles('./radas_dir')}}
see comments above

2024-03-29 18:42 UTC, tbody-cfs commented
```
from cfspopcon.read_atomic_data import AtomicData, AtomicSpecies
atomic_data = AtomicData()

from cfspopcon.atomic_data import read_atomic_data
atomic_data_2 = read_atomic_data()

for species in [
    "Helium",
    "Lithium",
    "Beryllium",
    "Carbon",
    "Nitrogen",
    "Oxygen",
    "Neon",
    "Argon",
    "Krypton",
    "Xenon",
    "Tungsten",
]:
    kind = AtomicData.CoronalLz

    dataset = atomic_data[species]

    Ne = np.logspace(np.log10(dataset.dim_electron_density.min()), np.log10(dataset.dim_electron_density.max()), num=1000, endpoint=False)
    Te = np.logspace(np.log10(dataset.dim_electron_temp.min()), np.log10(dataset.dim_electron_temp.max()), num=1000, endpoint=False)
    atomic_data.eval_interpolator(Ne, Te, kind=kind, species=species, allow_extrapolation=True).sel(dim_electron_density=1e20, method="nearest").plot(xscale="log", yscale="log", label="new")

    interpolator_2 = atomic_data_2[AtomicSpecies[species]].coronal_Lz_interpolator

    xr.DataArray(np.power(10, interpolator_2(np.log10(Te), np.log10(Ne), grid=True)), coords=dict(dim_electron_temp=Te, dim_electron_density=Ne)).sel(dim_electron_density=1e20, method="nearest").plot(xscale="log", yscale="log", label="original", linestyle="--")

    plt.title(f"{species} Lz ")
    plt.legend()

    plt.savefig(f"{species}_Lz.png")
    plt.close()
```
![Tungsten_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/0bfc7ad3-56bc-4537-9c0b-acbc6eff3687)
![Xenon_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/406d0716-f216-424d-ac97-496117127dfb)
![Krypton_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/d678401e-c063-435b-b6c4-1be7fc2fe31a)
![Argon_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/a8c85cd9-a3e7-46ed-afc4-00714b08a9b3)
![Neon_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/00d82665-ee2c-495d-ba17-fa187a821a3a)
![Oxygen_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/e2d5a776-ac97-430c-9261-b77a9fdf14ba)
![Nitrogen_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/45ce22a9-bbea-4165-9a6d-ac51f0a87df3)
![Carbon_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/60819fd8-1051-4184-bca7-d2267e8a1435)
![Beryllium_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/da467997-e7c2-4ffb-b038-4f81a0a8b1da)
![Lithium_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/f5555900-289a-422f-a999-2d70223ebe79)
![Helium_Z](https://github.com/cfs-energy/cfspopcon/assets/116750897/8abf999c-4613-4d9f-9d85-e6294b57c0e9)
![Tungsten_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/73812096-8c96-44c8-a6cf-8f57df083e53)
![Xenon_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/c2f60b26-08ff-4156-b932-d21914a9b02c)
![Krypton_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/3677c0e2-62ca-445a-a168-3b2018fe8a97)
![Argon_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/08ca86d9-b2da-48f9-bddd-5cb27e07955f)
![Neon_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/13d06059-3d5a-4bab-8051-4761f7b98001)
![Oxygen_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/cea2afd4-1ac2-4610-8a21-95fa429efa45)
![Nitrogen_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/e4a6635c-a17a-498d-8184-0ff534cf5fed)
![Carbon_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/fcf32c17-624a-4322-88cf-809178977313)
![Beryllium_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/8c46a9e9-1cc0-4557-a3af-65bdff92b5d4)
![Lithium_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/5f0b148d-00f4-428d-8341-5a3e1b152983)
![Helium_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/cb12f17d-9555-4c3a-a7a0-c26c456d4bdf)

2024-04-01 16:23 UTC, tbody-cfs commented on .github/workflows/workflow_actions.yml
>            path: radas
?

2024-04-01 21:17 UTC, tbody-cfs commented
Seems to be slower than the previous version. Why is this? Might want to try evaluate for the entire ne, Te grid at once. Alternatively, pick a single ne value (weak dependence for rates) and just use this single reference value.

2024-04-02 15:05 UTC, hassec approved these changes
Walked through this with @tbody-cfs in person. Comments already applied while we reviewed 🎉 

LGTM 🚀

2024-04-02 16:38 UTC, tbody-cfs commented
Checking the comparison of the Krypton data, was getting an issue where the Lz curve was going to zero at a particular temperature. Have now added logic to drop invalid rows and columns from the atomic data.

## Raw data

```
atomic_data[AtomicSpecies.Krypton].sel(dim_electron_density=1e20, method="nearest").coronal_Lz.plot(xscale="log", yscale="log")
plt.title("Krypton")
```
![image](https://github.com/cfs-energy/cfspopcon/assets/116750897/40cb8736-ce1b-41a2-9e6b-c1fcf94cfd01)

## New output of interpolator, dropping invalid values

![Krypton_Lz](https://github.com/cfs-energy/cfspopcon/assets/116750897/f17bee11-9e51-4128-a136-9c34a68ee81a)

2024-04-02 16:44 UTC, merged