draft: Tidy up variable naming
cfs-energy/cfspopcon pull request #80
Opened 2024-07-30 21:56 UTC by tbody-cfs

An idea for a tool that could be helpful.

We need to keep the `default_units` and `physics_glossary` up to date with the algorithm keys. We can try to do that manually, but it's a bit tedious. Instead, I implemented the following helper tool to make sure that these always stay consistent.

If this seems like a good idea, I'll polish it and add the units/glossary entries for everything there.

2024-07-31 13:10 UTC, hassec commented on cfspopcon/default_units.yaml
> +definition: UNKNOWN
What's `definition`?

2024-07-31 13:15 UTC, hassec commented on cfspopcon/key_checker.py
> +"""A simple tool to ensure consistency between the algorithms, default units and the physics glossary, with a CLI."""
I think we should move this script outside `cfspopcon` as a helper script which we can then run in CI to ensure things won't break. 

We could put it into a `tests/utils/` folder for example.

2024-07-31 13:16 UTC, hassec commented on cfspopcon/key_checker.py
> +        with as_file(files("cfspopcon").parents[0] / "docs" / "doc_sources" / "physics_glossary.rst") as filepath:  # type:ignore[attr-defined]
If we move the script you can just assume that the script is run from the repo, and won't need to use `as_file` patterns.

2024-07-31 13:21 UTC, hassec commented on cfspopcon/key_checker.py
> +                    algorithm_keys.append(key)
What do you think about directly making it a set and using `update` ? 
```suggestion
        algorithm_keys: set[str] = {}

        for alg in Algorithm.instances.values():
            algorithm_keys.update(alg.input_keys)
            algorithm_keys.update(alg.return_keys)
```

2024-07-31 14:27 UTC, tbody-cfs commented on cfspopcon/default_units.yaml
> +definition: UNKNOWN
I've renamed this to something clearer

2024-08-01 19:08 UTC, hassec requested changes
Minor set of comments, but excited to have this 👍

2024-08-01 19:08 UTC, hassec commented on tests/utils/variable_consistency_checker.py
> +                    set_by.append(alg._name)
could consider moving this out of the loop and traversing the algorithms list once to create a dict of key -> (used_by, set_by). Would avoid having to do this full loop for every key.

2024-08-01 20:54 UTC, tbody-cfs commented on tests/utils/variable_consistency_checker.py
> +        pattern_for_key = re.compile(r"^\s{2}[^\s]")
Made change, and also changed `pattern_for_description`.
```
pattern_for_key = re.compile(r"^\s{2}\S+\s*$")
pattern_for_description = re.compile(r"^\s{4}\S.+")
```

2024-08-01 22:31 UTC, hassec approved these changes

2024-08-02 00:25 UTC, merged